#**********************************************
#	This file was automatically generated 2020:05:16T18:12:00
#	
#	DO NOT EDIT THIS FILE -- Use Dialog Builder Tools to edit this file.
#***********************************************

import vs

# control IDs
kOK                   = 1
kCancel               = 2
kUnnamed              = 4
kscale1               = 6
kUnnamed3             = 8
ksize                 = 9

def CreateDialog():
    # Alignment constants
    kRight                = 1
    kBottom               = 2
    kLeft                 = 3
    kColumn               = 4
    kResize               = 0
    kShift                = 1

    def GetPluginString(ndx):
        # Static Text
        if ndx == 1001:			return 'Pick Folder'
        elif ndx == 1002:		return 'Cancel'
        elif ndx == 1003:		return 'Import Gobo Images'
        elif ndx == 1004:		return 'Scale'
        elif ndx == 1006:		return ''
        elif ndx == 1008:		return 'Diameter (inches)'
        elif ndx == 1009:		return ''
        # Help Text
        elif ndx == 2001:		return 'Pick a folder of images to import.'
        elif ndx == 2002:		return 'Cancels the import.'
        elif ndx == 2004:		return 'Scale factor for the image.'
        elif ndx == 2006:		return 'Scale factor for the image.'
        elif ndx == 2008:		return 'Diameter of the symbol after import.'
        elif ndx == 2009:		return 'Diameter of the symbol after import.'
        return ''

    def GetStr(ndx):
        result = GetPluginString( ndx + 1000 )
        return result

    def GetHelpStr(ndx):
        result = GetPluginString( ndx + 2000 )
        return result

    major = 0
    minor = 0
    maintenance = 0
    platform = 0
    major, minor, maintenance, platform = vs.GetVersion( major, minor, maintenance, platform )
    if (platform == 1): # IsMac
      v_scale    = 1.05
    else:
      v_scale    = 1.05

    dialog = vs.CreateLayout( GetStr(3), True, GetStr(kOK), GetStr(kCancel) )

    # create controls
    vs.CreateStaticText( dialog, kUnnamed, GetStr(kUnnamed), -1 )
    vs.CreateEditReal( dialog, kscale1, 1, 1.05, 16 )
    vs.CreateStaticText( dialog, kUnnamed3, GetStr(kUnnamed3), -1 )
    vs.CreateEditReal( dialog, ksize, 1, 24, 16 )

    # set relations
    vs.SetFirstLayoutItem( dialog, kUnnamed )
    vs.SetRightItem( dialog, kUnnamed, kscale1, 0, 0 )
    vs.SetBelowItem( dialog, kUnnamed, kUnnamed3, 0, 0 )
    vs.SetRightItem( dialog, kUnnamed3, ksize, 0, 0 )

    # set alignments
    vs.AlignItemEdge( dialog, kscale1, kRight, 4, kShift );
    vs.AlignItemEdge( dialog, ksize, kRight, 4, kShift );

    # set help strings
    cnt = 1
    while ( cnt <= 9 ):
        vs.SetHelpText( dialog, cnt, GetHelpStr(cnt) )
        cnt += 1

    return dialog

# Sample dialog handler
# Uncomment this code if you want to display the dialog
'''
def DialogHandler(item, data):
	pass

dlg = CreateDialog()
vs.RunLayoutDialog( dlg, DialogHandler )
'''

# XML defintion of the layout
#
# <BEGIN_XML>
#<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
# <DialogBuilder>
# 
#   <LayoutData>
#     <Name>dlg</Name>
#     <Title>Import Gobo Images</Title>
#     <OKText>Pick Folder</OKText>
#     <OKHelpText>Pick a folder of images to import.</OKHelpText>
#     <CancelText>Cancel</CancelText>
#     <CancelHelpText>Cancels the import.</CancelHelpText>
#     <ResizableWidth>FALSE</ResizableWidth>
#     <ResizableHeight>FALSE</ResizableHeight>
#     <StringsStartID>0</StringsStartID>
#     <HelpStrStartID>1</HelpStrStartID>
#     <TablesAddToDlgRes>TRUE</TablesAddToDlgRes>
#     <AltStringStartID>0</AltStringStartID>
#     <ResourceRoot>PluginModule_resource_file_vwr</ResourceRoot>
#     <Vars>
#       <Var>
#         <Name>v_scale</Name>
#         <Type>INTEGER</Type>
#         <WinValue>1.05</WinValue>
#         <MacValue>1.05</MacValue>
#       </Var>
#     </Vars>
#   </LayoutData>
# 
#   <Controls>
#     <Control name="DialogBuilderControl" x="0" y="0">
#       <Parameter Name="__UUID">{8B5E1DFD-B414-4141-9F70-F6A4B034F434}</Parameter>
#       <Parameter Name="id">4</Parameter>
#       <Parameter Name="constName">Unnamed</Parameter>
#       <Parameter Name="label">Scale</Parameter>
#       <Parameter Name="helpText">Scale factor for the image.</Parameter>
#       <Parameter Name="bindRight">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">76mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-2mm</Parameter>
#       <Parameter Name="ControlPoint01X">23mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-25mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__RightUUID">{20B7A8EB-C4FA-4456-8042-533F55DF4C5E}</Parameter>
#       <Parameter Name="__BottomUUID">{6D871561-ED25-48D0-9E77-D1D52DD73AC7}</Parameter>
#       <Parameter Name="__savedHandleRightX">76mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-2mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">23mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-25mm</Parameter>
#       <Parameter Name="__fVisControlWidth">10</Parameter>
#       <Parameter Name="__fVisControlHeight">4</Parameter>
#     </Control>
#     <Control name="DialogBuilderControl" x="76" y="0">
#       <Parameter Name="__UUID">{20B7A8EB-C4FA-4456-8042-533F55DF4C5E}</Parameter>
#       <Parameter Name="type">kEditRealBox</Parameter>
#       <Parameter Name="id">6</Parameter>
#       <Parameter Name="constName">scale1</Parameter>
#       <Parameter Name="value">1.05</Parameter>
#       <Parameter Name="helpText">Scale factor for the image.</Parameter>
#       <Parameter Name="alignGroup">4</Parameter>
#       <Parameter Name="alignMode">kShift</Parameter>
#       <Parameter Name="bindLeft">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">25mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-2mm</Parameter>
#       <Parameter Name="ControlPoint01X">12mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-4mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__savedHandleRightX">25mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-2mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">12mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-4mm</Parameter>
#       <Parameter Name="__arrAlignments">4|0|1;</Parameter>
#       <Parameter Name="__fVisControlWidth">25</Parameter>
#       <Parameter Name="__fVisControlHeight">4</Parameter>
#     </Control>
#     <Control name="DialogBuilderControl" x="0" y="-25">
#       <Parameter Name="__UUID">{6D871561-ED25-48D0-9E77-D1D52DD73AC7}</Parameter>
#       <Parameter Name="id">8</Parameter>
#       <Parameter Name="constName">Unnamed3</Parameter>
#       <Parameter Name="label">Diameter (inches)</Parameter>
#       <Parameter Name="helpText">Diameter of the symbol after import.</Parameter>
#       <Parameter Name="bindRight">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">50mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-2mm</Parameter>
#       <Parameter Name="ControlPoint01X">16mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-4mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__RightUUID">{13168647-397C-4231-9E84-0D16292DAE83}</Parameter>
#       <Parameter Name="__savedHandleRightX">50mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-2mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">16mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-4mm</Parameter>
#       <Parameter Name="__fVisControlWidth">33</Parameter>
#       <Parameter Name="__fVisControlHeight">4</Parameter>
#     </Control>
#     <Control name="DialogBuilderControl" x="50" y="-25">
#       <Parameter Name="__UUID">{13168647-397C-4231-9E84-0D16292DAE83}</Parameter>
#       <Parameter Name="type">kEditRealBox</Parameter>
#       <Parameter Name="id">9</Parameter>
#       <Parameter Name="constName">size</Parameter>
#       <Parameter Name="value">24</Parameter>
#       <Parameter Name="helpText">Diameter of the symbol after import.</Parameter>
#       <Parameter Name="alignGroup">4</Parameter>
#       <Parameter Name="alignMode">kShift</Parameter>
#       <Parameter Name="bindLeft">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">25mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-2mm</Parameter>
#       <Parameter Name="ControlPoint01X">12mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-4mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__savedHandleRightX">25mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-2mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">12mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-4mm</Parameter>
#       <Parameter Name="__arrAlignments">4|0|1;</Parameter>
#       <Parameter Name="__fVisControlWidth">25</Parameter>
#       <Parameter Name="__fVisControlHeight">4</Parameter>
#       <Parameter Name="altHelpText">Test</Parameter>
#     </Control>
#     <Control name="Dialog Builder Link" x="0" y="0">
#       <Parameter Name="ParentObj">{8B5E1DFD-B414-4141-9F70-F6A4B034F434}</Parameter>
#       <Parameter Name="RelatedObj">{6D871561-ED25-48D0-9E77-D1D52DD73AC7}</Parameter>
#       <Parameter Name="ParentMode">1</Parameter>
#     </Control>
#     <Control name="Dialog Builder Link" x="0" y="0">
#       <Parameter Name="ParentObj">{6D871561-ED25-48D0-9E77-D1D52DD73AC7}</Parameter>
#       <Parameter Name="RelatedObj">{13168647-397C-4231-9E84-0D16292DAE83}</Parameter>
#       <Parameter Name="ParentMode">0</Parameter>
#     </Control>
#     <Control name="Dialog Builder Link" x="0" y="0">
#       <Parameter Name="ParentObj">{8B5E1DFD-B414-4141-9F70-F6A4B034F434}</Parameter>
#       <Parameter Name="RelatedObj">{20B7A8EB-C4FA-4456-8042-533F55DF4C5E}</Parameter>
#       <Parameter Name="ParentMode">0</Parameter>
#     </Control>
#   </Controls>
# 
# </DialogBuilder>
# 
# <END_XML>

